import type { Product } from "@/lib/products/types";

/**
 * The full product catalog — the single source of truth for products,
 * prices, and specifications across the site. To add a product, add an
 * entry below and drop its image at /public/products/<MODEL>.webp (shown
 * automatically once present; a placeholder renders until then). To set a
 * price, change `priceIQD` from `null` to a number.
 *
 * Do not add HT-MCZ5000 or HT-1024 — explicitly excluded from this catalog.
 */
export const products: Product[] = [
  {
    slug: "ht-bsd5blt-m",
    model: "HT-BSD5BLT-M",
    name: "5MP AI powered Bullet IPC",
    category: "camera",
    image: "/products/HT-BSD5BLT-M.webp",
    priceIQD: null,
    features: [
      "5MP Sony Starvis Imaging Sensor",
      "H264/H264+/H265/H265+ Video Compression",
      "Professional Motorized Technology Auto-Focus Lens (2.7mm-13.5mm)",
      "90/sqm Smart LED for uniform brightness in low light",
      "Extra 110m Smart IR LED",
      "Starlight Super Low Light Sensor captures clear colour images in light levels as low as 0.005 Lux",
      "BLC",
      "HLC",
      "2DNR",
      "3D DNR",
      "AWB",
      "WDR",
      "HDR",
      "Built-in Condensor Microphone for sound recording",
      "AI powered for advanced detection and analytics",
      "3-axis design for wall and ceiling mounting",
      "Remote Access & Recording via NVR, Cloud, FTP, P2P, NAS, QNAP, etc.",
    ],
    specs: [
      { label: "الدقة", value: "5MP (25-fps) / 4MP (30-fps) / 2MP (60-fps)" },
      { label: "التغذية الكهربائية", value: "PoE 802.3at/af (6W) or 12V DC" },
      { label: "البروتوكول", value: "Hasnet, Xvision, Onvif PROFILE S, Onvif PROFILE G, Onvif PROFILE T" },
      { label: "درجة حرارة التشغيل", value: "-30 to 70 °C" },
      { label: "الأبعاد", value: "240mm x 80mm x 79mm" },
      { label: "الوزن", value: "0.780 kg" },
    ],
    capabilities: [
      "Human Detection: True",
      "Vehicle Detection: True",
      "IP67 Prevention: Ultra",
      "Sony Exmor Sensor",
      "Smart H.265+ Encoding",
      "Audio Processing Ready",
      "WDR Range Technology",
    ],
    accessories: ["Plastic Junction Box (JB-002)", "Metal Pole Bracket (JB-002A)"],
    warranty: "2 year warranty",
  },
  {
    slug: "ht-hsb6000",
    model: "HT-HSB6000",
    name: "6MP AI powered Bullet IPC",
    category: "camera",
    image: "/products/HT-HSB6000.webp",
    priceIQD: null,
    features: [
      "6MP Sony Starvis Imaging Sensor",
      "H264/H264+/H265/H265+ Video Compression",
      "Wide lens 2.8mm (99°)",
      "Normal view lens 4mm (79°)",
      "Narrow view lens 6mm (50°)",
      "45/sqm Smart LED for uniform brightness in low light",
      "Extra 50m Smart IR LED",
      "Starlight Super Low Light Sensor down to 0.005 Lux",
      "BLC",
      "HLC",
      "2DNR",
      "3D DNR",
      "AWB",
      "WDR",
      "HDR",
      "Built-in Condensor Microphone",
      "AI powered advanced detection and analytics",
      "3-axis mounting design",
      "Remote Access & Recording via NVR, Cloud, FTP, P2P, NAS, QNAP, etc.",
    ],
    specs: [
      { label: "الدقة", value: "6MP (25-fps) / 4MP (30-fps) / 2MP (30-fps)" },
      { label: "التغذية الكهربائية", value: "PoE 802.3at/af (6W) or 12V DC" },
      { label: "البروتوكول", value: "Hasnet, Xvision, Onvif PROFILE S, PROFILE G, PROFILE T" },
      { label: "درجة حرارة التشغيل", value: "-30 to 70 °C" },
      { label: "الأبعاد", value: "170mm x 68mm x 68mm" },
      { label: "الوزن", value: "0.465 kg" },
    ],
    capabilities: [
      "Human Detection",
      "Vehicle Detection",
      "IP67 Prevention",
      "Sony Exmor Sensor",
      "H.265+",
      "Audio Processing",
      "WDR",
    ],
    accessories: ["Plastic Junction Box (JB-002)"],
    warranty: "2 year warranty",
  },
  {
    slug: "ht-bsd6blt",
    model: "HT-BSD6BLT",
    name: "6MP AI powered Bullet IPC",
    category: "camera",
    image: "/products/HT-BSD6BLT.webp",
    priceIQD: null,
    features: [
      "6MP Sony Starvis Imaging Sensor",
      "H264/H264+/H265/H265+ Video Compression",
      "2.8mm (99°), 4mm (79°), 6mm (50°) lens options",
      "90/sqm Smart LED",
      "Extra 110m Smart IR LED",
      "Starlight Super Low Light Sensor down to 0.005 Lux",
      "BLC",
      "HLC",
      "2DNR",
      "3D DNR",
      "AWB",
      "WDR",
      "HDR",
      "Built-in Condensor Microphone",
      "AI powered advanced detection and analytics",
      "3-axis mounting",
      "Remote access and recording support",
    ],
    specs: [
      { label: "الدقة", value: "8MP (15-fps) / 6MP (25-fps) / 4MP (30-fps)" },
      { label: "التغذية الكهربائية", value: "PoE 802.3at/af (6W) or 12V DC" },
      { label: "البروتوكول", value: "Hasnet, Xvision, Onvif PROFILE S/G/T" },
      { label: "درجة حرارة التشغيل", value: "-30 to 70 °C" },
      { label: "الأبعاد", value: "240mm x 80mm x 79mm" },
      { label: "الوزن", value: "0.705 kg" },
    ],
    accessories: ["Plastic Junction Box (JB-002)"],
    warranty: "2 year warranty",
  },
  {
    slug: "ht-hesu8mp",
    model: "HT-HESU8MP",
    name: "8MP AI powered Bullet IPC",
    category: "camera",
    image: "/products/HT-HESU8MP.webp",
    priceIQD: null,
    features: [
      "8MP Sony Starvis Imaging Sensor",
      "H264/H264+/H265/H265+ Video Compression",
      "Lens options 2.8mm / 4mm / 6mm",
      "35/sqm Smart LED",
      "Extra 40m Smart IR LED",
      "Starlight Super Low Light Sensor down to 0.005 Lux",
      "BLC",
      "HLC",
      "2DNR",
      "3D DNR",
      "AWB",
      "WDR",
      "HDR",
      "Built-in Condensor Microphone",
      "AI advanced detection and analytics",
      "3-axis mounting",
      "Remote access and recording",
    ],
    specs: [
      { label: "الدقة", value: "8MP (20-fps) / 5MP (30-fps) / 2MP (30-fps)" },
      { label: "التغذية الكهربائية", value: "PoE 802.3at/af (6W) or 12V DC" },
      { label: "البروتوكول", value: "Hasnet, Xvision, Onvif PROFILE S/G/T" },
      { label: "درجة حرارة التشغيل", value: "-30 to 70 °C" },
      { label: "الأبعاد", value: "170mm x 68mm x 68mm" },
      { label: "الوزن", value: "0.465 kg" },
    ],
    accessories: ["Plastic Junction Box (JB-002)"],
    warranty: "2 year warranty",
  },
  {
    slug: "ht-cha12000",
    model: "HT-CHA12000",
    name: "12MP AI powered Bullet IPC",
    category: "camera",
    image: "/products/HT-CHA12000.webp",
    priceIQD: null,
    features: [
      "12MP Sony Starvis Imaging Sensor",
      "H264/H264+/H265/H265+ Video Compression",
      "Lens options 2.8mm / 4mm / 6mm",
      "75/sqm Smart LED",
      "Extra 80m Smart IR LED",
      "Starlight Super Low Light Sensor down to 0.005 Lux",
      "BLC",
      "HLC",
      "2DNR",
      "3D DNR",
      "AWB",
      "WDR",
      "HDR",
      "Built-in Condensor Microphone",
      "AI advanced detection and analytics",
      "3-axis mounting",
      "Remote access and recording",
    ],
    specs: [
      { label: "الدقة", value: "12MP (15-fps) / 10MP (20-fps) / 6MP (30-fps)" },
      { label: "التغذية الكهربائية", value: "PoE 802.3at/af (6W) or 12V DC" },
      { label: "البروتوكول", value: "Hasnet, Xvision, Onvif PROFILE S/G/T" },
      { label: "درجة حرارة التشغيل", value: "-30 to 70 °C" },
      { label: "الأبعاد", value: "170mm x 68mm x 68mm" },
      { label: "الوزن", value: "0.415 kg" },
    ],
    accessories: ["Plastic Junction Box (JB-002)"],
    warranty: "2 year warranty",
  },
  {
    slug: "ht-bsd12blt-m",
    model: "HT-BSD12BLT-M",
    name: "12MP AI powered Bullet IPC",
    category: "camera",
    image: "/products/HT-BSD12BLT-M.webp",
    priceIQD: null,
    features: [
      "12MP Sony Starvis Imaging Sensor",
      "H264/H264+/H265/H265+ Video Compression",
      "Professional Motorized Auto-Focus Lens (3.6mm-11mm)",
      "100/sqm Smart LED",
      "Extra 105m Smart IR LED",
      "Starlight Super Low Light Sensor down to 0.001 Lux",
      "BLC",
      "HLC",
      "2DNR",
      "3D DNR",
      "AWB",
      "WDR",
      "HDR",
      "Built-in Condensor Microphone",
      "AI advanced detection and analytics",
      "3-axis mounting",
      "Remote access and recording",
    ],
    specs: [
      { label: "الدقة", value: "12MP (25-fps) / 8MP (30-fps) / 4MP (60-fps)" },
      { label: "التغذية الكهربائية", value: "PoE 802.3at/af (6W) or 12V DC" },
      { label: "البروتوكول", value: "Hasnet, Xvision, Onvif PROFILE S/G/T" },
      { label: "درجة حرارة التشغيل", value: "-30 to 70 °C" },
      { label: "الأبعاد", value: "280mm x 80mm x 89mm" },
      { label: "الوزن", value: "0.900 kg" },
    ],
    accessories: ["Plastic Junction Box (JB-002)", "Metal Pole Bracket (JB-002A)"],
    warranty: "2 year warranty",
  },
  {
    slug: "ht-esd5mp",
    model: "HT-ESD5MP",
    name: "5MP AI powered Camera",
    category: "camera",
    image: "/products/HT-ESD5MP.webp",
    priceIQD: null,
    features: [
      "5MP Sony Starvis Imaging Sensor",
      "H264/H264+/H265/H265+ Video Compression",
      "Lens options 2.8mm / 4mm / 6mm",
      "35/sqm Smart LED",
      "Extra 40m Smart IR LED",
      "Starlight Super Low Light Sensor down to 0.005 Lux",
      "BLC",
      "HLC",
      "2DNR",
      "3D DNR",
      "AWB",
      "WDR",
      "HDR",
      "Built-in Condensor Microphone",
      "AI advanced detection",
      "Remote access and recording",
    ],
    specs: [
      { label: "الدقة", value: "5MP (20-fps) / 4MP (25-fps) / 2MP (30-fps)" },
      { label: "التغذية الكهربائية", value: "PoE 802.3at/af (6W) or 12V DC" },
      { label: "البروتوكول", value: "Hasnet, Xvision, Onvif PROFILE S/G/T" },
      { label: "درجة حرارة التشغيل", value: "-30 to 70 °C" },
      { label: "الأبعاد", value: "100mm x 95mm" },
      { label: "الوزن", value: "0.360 kg" },
    ],
    accessories: ["Plastic Junction Box (JB-002)", "Wall Bracket with integrated Junction Box (WB-005)"],
    warranty: "2 year warranty",
  },
  {
    slug: "ht-qd6mp",
    model: "HT-QD6MP",
    name: "6MP AI powered Camera",
    category: "camera",
    image: "/products/HT-QD6MP.webp",
    priceIQD: null,
    features: [
      "6MP Sony Starvis Imaging Sensor",
      "H264/H264+/H265/H265+ Video Compression",
      "Lens options 2.8mm / 4mm / 6mm",
      "40/sqm Smart LED",
      "Extra 45m Smart IR LED",
      "Starlight Super Low Light Sensor down to 0.005 Lux",
      "BLC",
      "HLC",
      "2DNR",
      "3D DNR",
      "AWB",
      "WDR",
      "HDR",
      "Built-in Condensor Microphone",
      "AI advanced detection",
      "Remote access and recording",
    ],
    specs: [
      { label: "الدقة", value: "6MP (25-fps) / 5MP (25-fps) / 4MP (30-fps)" },
      { label: "التغذية الكهربائية", value: "PoE 802.3at/af (6W) or 12V DC" },
      { label: "البروتوكول", value: "Hasnet, Xvision, Onvif PROFILE S/G/T" },
      { label: "درجة حرارة التشغيل", value: "-30 to 70 °C" },
      { label: "الأبعاد", value: "100mm x 95mm" },
      { label: "الوزن", value: "0.390 kg" },
    ],
    accessories: ["Plastic Junction Box (JB-002)", "Wall Bracket with integrated Junction Box (WB-005)"],
    warranty: "2 year warranty",
  },
  {
    slug: "ht-12912hth",
    model: "HT-12912HTH",
    name: "12 Channel AI powered NVR",
    category: "nvr",
    image: "/products/HT-12912HTH.webp",
    priceIQD: null,
    features: [
      "Supports IPC manufacturers including Hasnet, Xvision, Hikvision, Dahua, Uniview, Axis, Bosch, XM, Sony, Huawei, TVT, JVT, Google and more",
      "AI enabled for Hasnet and Xvision AI cameras",
      "Remote Viewing App",
      "Desktop software for PC",
      "iOS and Android support",
      "Live Viewing",
      "Playback",
      "Configuration of up to 64 NVRs & IPCs",
      "Real-Time Online Update for NVR and connected IPC",
    ],
    specs: [
      { label: "دعم الكاميرات", value: "12 Cameras @ 4K (3840×2160) / 9 Cameras @ 8K (4000×3000)" },
      { label: "ضغط الفيديو", value: "H.265+, H.265, H.264 IPC adaptive compatibility" },
      { label: "أقصى تشغيل متزامن", value: "4 channels" },
      { label: "قدرة التشغيل", value: "1-ch @ 12MP / 8MP, 4-ch @ 4MP" },
      { label: "خرج الفيديو", value: "1x HDMI 4K, VGA independent outputs" },
      { label: "الدقة", value: "UHD 4K" },
      { label: "ONVIF", value: "Version 24.06 (2024/June) and below" },
      { label: "منفذ الشبكة", value: "1x 1000Mbps" },
      { label: "أقصى سعة قرص صلب", value: "1x14TB" },
      { label: "USB", value: "2 back, Type 3.0" },
      { label: "الإنذار", value: "20 Channel Alarm Electronic Output" },
      { label: "خرج الصوت", value: "1-ch RCA (Linear, 1 KΩ)" },
      { label: "الاتصالات عن بعد", value: "10" },
      { label: "تطبيق التحكم عن بعد", value: "Video Link, AC180 Pro" },
      { label: "طريقة التركيب", value: "Desktop Mount" },
      { label: "مزود الطاقة", value: "12VDC 5A" },
      { label: "استهلاك الطاقة", value: "8W" },
    ],
    warranty: "2 years including Manufacturing R&D Updates",
  },
  {
    slug: "ht-2020hth",
    model: "HT-2020HTH",
    name: "20 Channel AI powered NVR",
    category: "nvr",
    image: "/products/HT-2020HTH.webp",
    priceIQD: null,
    features: [
      "Supports IPC manufacturers including Hasnet, Xvision, Hikvision, Dahua, Uniview, Axis, Bosch, XM, Sony, Huawei, TVT, JVT, Google and more",
      "AI enabled for Hasnet and Xvision AI cameras",
      "Remote Viewing App",
      "Desktop software for PC",
      "iOS and Android support",
      "Live Viewing",
      "Playback",
      "Configuration of up to 64 NVRs & IPCs",
      "Real-Time Online Update for NVR and connected IPC",
    ],
    specs: [
      { label: "دعم الكاميرات", value: "20 Cameras @ 8K (4000×3000)" },
      { label: "ضغط الفيديو", value: "H.265+, H.265, H.264 IPC adaptive compatibility" },
      { label: "أقصى تشغيل متزامن", value: "4 channels" },
      { label: "قدرة التشغيل", value: "1-ch @ 12MP / 8MP, 4-ch @ 4MP" },
      { label: "خرج الفيديو", value: "1x HDMI 4K, VGA" },
      { label: "الدقة", value: "UHD 4K" },
      { label: "ONVIF", value: "Version 24.06 and below" },
      { label: "منفذ الشبكة", value: "1x 1000Mbps" },
      { label: "أقصى سعة قرص صلب", value: "1x14TB" },
      { label: "USB", value: "2 back Type 3.0" },
      { label: "الإنذار", value: "20 Channel Alarm Electronic Output" },
      { label: "خرج الصوت", value: "1-ch RCA" },
      { label: "الاتصالات عن بعد", value: "10" },
      { label: "تطبيق التحكم عن بعد", value: "Video Link, AC180 Pro" },
      { label: "طريقة التركيب", value: "Desktop Mount" },
      { label: "مزود الطاقة", value: "12VDC 5A" },
      { label: "استهلاك الطاقة", value: "8W" },
    ],
    warranty: "2 years including Manufacturing R&D Updates",
  },
  {
    slug: "ht-3636212hth",
    model: "HT-3636212HTH",
    name: "36 Channel AI powered NVR",
    category: "nvr",
    image: "/products/HT-3636212HTH.webp",
    priceIQD: null,
    features: [],
    specs: [
      { label: "دعم الكاميرات", value: "36 Cameras @ 8K (4000×3000)" },
      { label: "ضغط الفيديو", value: "H.265+, H.265, H.264 IPC adaptive compatibility" },
      { label: "أقصى تشغيل متزامن", value: "4 channels" },
      { label: "قدرة التشغيل", value: "2-ch @ 12MP / 8MP, 4-ch @ 4MP" },
      { label: "خرج الفيديو", value: "1x HDMI 4K, VGA" },
      { label: "الدقة", value: "UHD 4K" },
      { label: "ONVIF", value: "Version 24.06 and below" },
      { label: "منفذ الشبكة", value: "1x 1000Mbps" },
      { label: "أقصى سعة قرص صلب", value: "2x14TB" },
      { label: "USB", value: "2 back Type 3.0" },
      { label: "الإنذار", value: "20 Channel Alarm Electronic Output" },
      { label: "خرج الصوت", value: "1-ch RCA" },
      { label: "الاتصالات عن بعد", value: "10" },
      { label: "تطبيق التحكم عن بعد", value: "Video Link, AC180 Pro" },
      { label: "طريقة التركيب", value: "Desktop Mount" },
      { label: "مزود الطاقة", value: "12VDC 5A" },
      { label: "استهلاك الطاقة", value: "16W" },
    ],
    warranty: "2 years including Manufacturing R&D Updates",
  },
  {
    slug: "ht-6428hth",
    model: "HT-6428HTH",
    name: "64 Channel AI powered NVR",
    category: "nvr",
    image: "/products/HT-6428HTH.webp",
    priceIQD: null,
    features: [],
    specs: [
      { label: "دعم الكاميرات", value: "64 Cameras @ 4K (3840×2160) / 42 Cameras @ 8K (4000×3000)" },
      { label: "ضغط الفيديو", value: "H.265+, H.265, H.264 IPC adaptive compatibility" },
      { label: "أقصى تشغيل متزامن", value: "8 channels" },
      { label: "قدرة التشغيل", value: "4-ch @ 12MP, 4-ch @ 8MP, 16-ch @ 2MP" },
      { label: "خرج الفيديو", value: "2x HDMI 4K, VGA" },
      { label: "الدقة", value: "UHD 4K" },
      { label: "ONVIF", value: "Version 24.06 and below" },
      { label: "منفذ الشبكة", value: "2x 1000Mbps" },
      { label: "أقصى سعة قرص صلب", value: "8x14TB + External SATA Port" },
      { label: "USB", value: "2 back Type 3.0, 1 front Type 2.0" },
      { label: "الإنذار", value: "20 Channel Alarm Electronic Output" },
      { label: "خرج الصوت", value: "1-ch RCA" },
      { label: "الاتصالات عن بعد", value: "16" },
      { label: "تطبيق التحكم عن بعد", value: "Video Link, AC180 Pro" },
      { label: "طريقة التركيب", value: "Rack Mount, Desktop Mount" },
      { label: "مزود الطاقة", value: "220VAC to ATX Power Supply" },
      { label: "استهلاك الطاقة", value: "350W" },
    ],
    warranty: "2 years including Manufacturing R&D Updates",
  },
  {
    slug: "ht-1028",
    model: "HT-1028",
    name: "8 Port AI powered POE Switch",
    category: "switch",
    image: "/products/HT-1028.webp",
    priceIQD: null,
    features: [
      "Supports IP cameras, VoIP phones and other PoE devices",
      "AI enabled for Hasnet and Xvision AI cameras",
      "Easy setup without additional configuration",
      "PoE cable length support up to 100 meters",
      "Up to 250 meters using extender switch",
      "Suitable for IP CCTV Lithium UPS",
      "Supports both AC220VAC and 52VDC inputs",
      "AI Watchdog Technology",
    ],
    specs: [
      { label: "المنافذ", value: "10 Total, 8 PoE, 2 Uplink" },
      { label: "المعيار", value: "IEEE 802.3af/at/bt" },
      { label: "منافذ خاصة", value: "Port No.4 and No.8 support BT 60W" },
      { label: "مزود الطاقة", value: "1236 power supply" },
      { label: "سعة السويتش", value: "20Gb/s" },
      { label: "منافذ PoE", value: "8x100Mbps" },
      { label: "منافذ Uplink", value: "2x100Mbps" },
      { label: "دخل الطاقة", value: "220VAC or 52VDC" },
      { label: "طاقة PoE الكلية", value: "120W, Up to 135W Peak" },
      { label: "AI Watchdog", value: "Automatic restart when crashed" },
      { label: "درجة حرارة التشغيل", value: "-10 to 82 °C" },
      { label: "نظام التبريد", value: "Fanless Technology" },
      { label: "طريقة التركيب", value: "Desktop Mount, Wall Hanging" },
    ],
    accessories: [
      "Hasnet Indoor POE Extender HT-14A",
      "Hasnet Indoor POE Extender HT-13A",
      "Hasnet Outdoor POE Extender HT-13B",
      "Hasnet Outdoor POE Extender HT-14B",
      "Hasnet 48VDC 3A AC Adapter HT-4803",
    ],
    warranty: "2 years including Manufacturing Faults",
  },
];
